name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build flake package (aarch64-linux)
        id: build
        run: |
          set -euo pipefail
          # Build the ARM package so it matches your NixOS server
          out_path=$(nix build --no-link --print-out-paths .#packages.aarch64-linux.fixed-calendar)
          echo "out_path=$out_path" >> "$GITHUB_OUTPUT"
          echo "Built: $out_path"

      - name: Sign build outputs (recursive)
        env:
          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${NIX_SIGNING_KEY:-}" ]; then
            echo "NIX_SIGNING_KEY not set; skipping signing step." >&2
          else
            printf "%s" "$NIX_SIGNING_KEY" > ci-signing.key
            chmod 600 ci-signing.key
            nix store sign --recursive --key-file ci-signing.key "${{ steps.build.outputs.out_path }}"
            echo "Signed store path and closure."
            echo "Public key (add to server trusted-public-keys):"
            nix key convert-secret-to-public < ci-signing.key | sed 's/^/  /'
          fi

      - name: Prepare SSH
        env:
          SSH_KEY: ${{ secrets.NIX_SSH_KEY }}
          SSH_HOST: ${{ secrets.NIX_SSH_HOST }}
        run: |
          set -euo pipefail
          install -m 700 -d ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Copy closure to server
        env:
          SSH_HOST: ${{ secrets.NIX_SSH_HOST }}
          SSH_USER: ${{ secrets.NIX_SSH_USER }}
        run: |
          set -euo pipefail
          export NIX_SSHOPTS="-i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=yes"
          nix copy --to ssh-ng://$SSH_USER@$SSH_HOST "${{ steps.build.outputs.out_path }}"

      - name: Update user systemd service and restart
        env:
          SSH_HOST: ${{ secrets.NIX_SSH_HOST }}
          SSH_USER: ${{ secrets.NIX_SSH_USER }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_PORT: ${{ secrets.APP_PORT }}
          OUT_PATH: ${{ steps.build.outputs.out_path }}
        run: |
          set -euo pipefail
          export SSH="ssh -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=yes"
          # Pass vars into remote env; keep heredoc literal
          $SSH "$SSH_USER@$SSH_HOST" APP_NAME="$APP_NAME" APP_PORT="$APP_PORT" OUT_PATH="$OUT_PATH" bash -s <<'EOF'
          set -euo pipefail
          UNIT_DIR="$HOME/.config/systemd/user"
          mkdir -p "$UNIT_DIR"
          cat > "$UNIT_DIR/${APP_NAME}.service" <<UNIT
          [Unit]
          Description=${APP_NAME} (Fixed Calendar Bun app)
          After=network.target

          [Service]
          Environment=PORT=${APP_PORT}
          ExecStart=${OUT_PATH}/bin/fixed-calendar-start
          Restart=always

          [Install]
          WantedBy=default.target
          UNIT

          systemctl --user daemon-reload
          systemctl --user enable --now "$APP_NAME"
          systemctl --user restart "$APP_NAME"
          systemctl --user status "$APP_NAME" --no-pager -l || true
          EOF
